name: Continuous Integration and Deployment
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-test-format:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout code
      - uses: actions/checkout@v4

      - name: Build .NET application
        run : |
            dotnet clean
            dotnet restore
            dotnet build --configuration Release
